//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.Payments = new HashSet<Payment>();
        }
    
        public int AccountID { get; set; }
        public int UserID { get; set; }
        public int AccountTypeID { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public int CreatedUser { get; set; }
        public System.DateTime UpdatedDateTime { get; set; }
        public int UpdatedUser { get; set; }
        public decimal AccountBalance { get; set; }
    
        public virtual AccountType AccountType { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
    }
}
