//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountType
    {
        public AccountType()
        {
            this.Accounts = new HashSet<Account>();
        }
    
        public int AccountTypeID { get; set; }
        public string Type { get; set; }
    
        public virtual ICollection<Account> Accounts { get; set; }
        public virtual AccountType AccountType1 { get; set; }
        public virtual AccountType AccountType2 { get; set; }
    }
}
