//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Accounts = new HashSet<Account>();
            this.Payments = new HashSet<Payment>();
            this.UserRoles = new HashSet<UserRole>();
        }
    
        public int UserID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string UserName { get; set; }
        public bool PasswordNeverExpire { get; set; }
        public Nullable<int> DaysPasswordExpire { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<Account> Accounts { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
        public virtual ICollection<UserRole> UserRoles { get; set; }
    }
}
